name: Build, Push Docker Image and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React App (optional)
        run: npm run build --if-present

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: elhanafi856/react-shopping-cart:latest

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on remote server
        run: |
          ssh -o StrictHostKeyChecking=no user@ip_de_ta_vm << 'EOF'
            echo "Pull latest Docker image"
            sudo docker pull elhanafi856/react-shopping-cart:latest

            echo "Stop and remove old containers"
            sudo docker stop $(sudo docker ps -q --filter ancestor=elhanafi856/react-shopping-cart) || true
            sudo docker rm $(sudo docker ps -a -q --filter ancestor=elhanafi856/react-shopping-cart) || true

            echo "Run new container"
            sudo docker run -d -p 3000:3000 --restart unless-stopped --name react-shopping-cart elhanafi856/react-shopping-cart:latest
          EOF
