name: dev
on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: elhanafi856/app-dev:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to remote server via SSH (Dev)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_DEV }}
          username: ${{ secrets.SSH_USER_DEV }}
          key: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
          port: ${{ secrets.SSH_PORT_DEV }}
          script: |
            echo "Pull latest Docker image (Dev)"
            docker pull elhanafi856/app-dev:latest

            echo "Stop and remove old container if exists (Dev)"
            docker stop app-dev || true
            docker rm app-dev || true

            echo "Run new container (Dev)"
            docker run -d -p 3001:3000 --restart unless-stopped --name app-dev elhanafi856/app-dev:latest
